name: desktop
description: "Dhandas - Modern Accounting and Business Management Software"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  http: ^1.2.2
  excel: ^4.0.3
  flutter_riverpod: ^2.6.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  intl: ^0.17.0
  web_socket_channel: ^3.0.1

  # Cross-platform icons & printing/PDF support
  cupertino_icons: ^1.0.8
  printing: ^5.14.3
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # -------------------------------------------------------
  # Dhandas UI Images & Assets
  # -------------------------------------------------------
  assets:
    - assets/images/
    - lib/api/helpers/hsn.json